### PR TITLE
Refactor build script using modern CMake

### PR DESCRIPTION
**Pull request by hobywan**
This PR fixes the build failure in #42 when no compressors is used.

### CODE REVIEW

**Comment by hobywan** [comment]
@jpulidojr Thanks.
I was about to fix the HDF5 issue on Travis.

**Comment by hobywan** [comment]
May be we should just enable `C` as an additional language for `CBench`.
I will do a commit.

**Comment by hobywan** [comment]
Fixed

**Comment by jpulidojr** [comment]
Yes, the language definition as C and CXX seems to have fixed it

**Pull request merged**
